export type ToolId = "default" | "wide_sickle" | "fast_sickle" | "bomb_sickle" | "tractor";

export type SkillBranch =
  | "root"
  | "blade"
  | "movement"
  | "harvest"
  | "obstacles"
  | "bombs"
  | "land"
  | "spectacle";

export type UnlockGate =
  | { kind: "bestClearPercent"; mapSize: number; percent: number }
  | { kind: "lifetimeGrass"; count: number }
  | { kind: "bestBombChain"; length: number };

export type SkillEffect =
  | { kind: "attackDamage"; amount: number }
  | { kind: "attackRange"; amount: number }
  | { kind: "attackInterval"; amount: number }
  | { kind: "moveSpeed"; amount: number }
  | { kind: "roundDurationPercent"; amount: number }
  | { kind: "goldDivisor"; amount: number }
  | { kind: "cleanPatchScore"; amount: number }
  | { kind: "clearBonusPercent"; amount: number }
  | { kind: "rockScore"; amount: number }
  | { kind: "treeScore"; amount: number }
  | { kind: "stumpNoCollision" }
  | { kind: "failedChopStunPercent"; amount: number }
  | { kind: "obstacleDamage"; amount: number }
  | { kind: "obstacleBreakGrassBonus" }
  | { kind: "obstacleScorePercent"; amount: number }
  | { kind: "bombCount10m"; amount: number }
  | { kind: "bombChainRadius"; amount: number }
  | { kind: "bombBlastRadius"; amount: number }
  | { kind: "bombChainScore"; amount: number }
  | { kind: "firstBombScorePercent"; amount: number }
  | { kind: "unlockMap"; mapSize: number }
  | { kind: "initialGrassCount"; amount: number }
  | { kind: "grassScorePercent"; amount: number }
  | { kind: "toolUnlock"; tool: ToolId }
  | { kind: "special"; id: "cyclone_cut" | "sprint_harvest" | "golden_field" | "clearcut" | "alien_crop_mark" | "mower_laser" };

export interface SkillNode {
  id: string;
  name: string;
  branch: SkillBranch;
  icon: string;
  cost: number;
  prereq: string[];
  gates: UnlockGate[];
  effects: SkillEffect[];
  description: string;
}

export const SKILL_ROOT = "root_sharpen";

export const SKILL_NODES: SkillNode[] = [
  {
    id: "root_sharpen",
    name: "First Sharpening",
    branch: "root",
    icon: "R",
    cost: 10,
    prereq: [],
    gates: [],
    effects: [{ kind: "attackDamage", amount: 1 }],
    description: "Damage +1.",
  },
  {
    id: "sharp_edge_1",
    name: "Sharp Edge I",
    branch: "blade",
    icon: "B1",
    cost: 18,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "attackDamage", amount: 1 }],
    description: "Damage +1. Reaches one-hit grass with root.",
  },
  {
    id: "sharp_edge_2",
    name: "Sharp Edge II",
    branch: "blade",
    icon: "B2",
    cost: 60,
    prereq: ["sharp_edge_1"],
    gates: [],
    effects: [{ kind: "attackDamage", amount: 1 }],
    description: "Damage +1. Reaches obstacle break threshold.",
  },
  {
    id: "clean_sweep_1",
    name: "Clean Sweep I",
    branch: "blade",
    icon: "R1",
    cost: 28,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.1 }],
    description: "Attack range +0.10m.",
  },
  {
    id: "clean_sweep_2",
    name: "Clean Sweep II",
    branch: "blade",
    icon: "R2",
    cost: 90,
    prereq: ["clean_sweep_1"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.12 }],
    description: "Attack range +0.12m.",
  },
  {
    id: "quick_recovery_1",
    name: "Quick Recovery I",
    branch: "blade",
    icon: "Q1",
    cost: 35,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "attackInterval", amount: -100 }],
    description: "Attack interval -100ms.",
  },
  {
    id: "quick_recovery_2",
    name: "Quick Recovery II",
    branch: "blade",
    icon: "Q2",
    cost: 130,
    prereq: ["quick_recovery_1"],
    gates: [],
    effects: [{ kind: "attackInterval", amount: -100 }],
    description: "Attack interval -100ms.",
  },
  {
    id: "heavy_edge",
    name: "Heavy Edge",
    branch: "blade",
    icon: "HB",
    cost: 110,
    prereq: ["sharp_edge_2"],
    gates: [],
    effects: [
      { kind: "attackDamage", amount: 1 },
      { kind: "obstacleDamage", amount: 1 },
    ],
    description: "Damage +1 and obstacle damage +1.",
  },
  {
    id: "cyclone_cut",
    name: "Cyclone Cut",
    branch: "blade",
    icon: "CY",
    cost: 1200,
    prereq: ["clean_sweep_2", "quick_recovery_2"],
    gates: [],
    effects: [{ kind: "special", id: "cyclone_cut" }],
    description: "Every 6th attack performs a 0.85m circle cut.",
  },
  {
    id: "light_boots_1",
    name: "Light Boots I",
    branch: "movement",
    icon: "M1",
    cost: 14,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "moveSpeed", amount: 0.12 }],
    description: "Move speed +0.12.",
  },
  {
    id: "light_boots_2",
    name: "Light Boots II",
    branch: "movement",
    icon: "M2",
    cost: 55,
    prereq: ["light_boots_1"],
    gates: [],
    effects: [{ kind: "moveSpeed", amount: 0.14 }],
    description: "Move speed +0.14.",
  },
  {
    id: "field_rhythm_1",
    name: "Field Rhythm I",
    branch: "movement",
    icon: "T1",
    cost: 32,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "roundDurationPercent", amount: 8 }],
    description: "Round duration +8%.",
  },
  {
    id: "field_rhythm_2",
    name: "Field Rhythm II",
    branch: "movement",
    icon: "T2",
    cost: 125,
    prereq: ["field_rhythm_1"],
    gates: [],
    effects: [{ kind: "roundDurationPercent", amount: 8 }],
    description: "Round duration +8%.",
  },
  {
    id: "sprint_harvest",
    name: "Sprint Harvest",
    branch: "movement",
    icon: "SP",
    cost: 260,
    prereq: ["light_boots_2", "clean_rows_1"],
    gates: [],
    effects: [{ kind: "special", id: "sprint_harvest" }],
    description: "After a clean patch, move speed +20% for 2s.",
  },
  {
    id: "long_day",
    name: "Long Day",
    branch: "movement",
    icon: "LD",
    cost: 700,
    prereq: ["field_rhythm_2"],
    gates: [],
    effects: [{ kind: "roundDurationPercent", amount: 12 }],
    description: "Round duration +12%.",
  },
  {
    id: "market_cart_1",
    name: "Market Cart I",
    branch: "harvest",
    icon: "H1",
    cost: 20,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "goldDivisor", amount: -0.3 }],
    description: "Gold divisor 4.0 -> 3.7.",
  },
  {
    id: "market_cart_2",
    name: "Market Cart II",
    branch: "harvest",
    icon: "H2",
    cost: 80,
    prereq: ["market_cart_1"],
    gates: [],
    effects: [{ kind: "goldDivisor", amount: -0.3 }],
    description: "Gold divisor 3.7 -> 3.4.",
  },
  {
    id: "clean_rows_1",
    name: "Clean Rows I",
    branch: "harvest",
    icon: "C1",
    cost: 26,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "cleanPatchScore", amount: 8 }],
    description: "Clean patch bonus +8 score.",
  },
  {
    id: "clean_rows_2",
    name: "Clean Rows II",
    branch: "harvest",
    icon: "C2",
    cost: 110,
    prereq: ["clean_rows_1"],
    gates: [],
    effects: [{ kind: "cleanPatchScore", amount: 14 }],
    description: "Clean patch bonus +14 score.",
  },
  {
    id: "bulk_buyer_1",
    name: "Bulk Buyer I",
    branch: "harvest",
    icon: "P1",
    cost: 75,
    prereq: ["market_cart_1"],
    gates: [],
    effects: [{ kind: "clearBonusPercent", amount: 10 }],
    description: "Clear percent bonus +10%.",
  },
  {
    id: "bulk_buyer_2",
    name: "Bulk Buyer II",
    branch: "harvest",
    icon: "P2",
    cost: 210,
    prereq: ["bulk_buyer_1"],
    gates: [],
    effects: [{ kind: "clearBonusPercent", amount: 15 }],
    description: "Clear percent bonus +15%.",
  },
  {
    id: "golden_field",
    name: "Golden Field",
    branch: "harvest",
    icon: "GF",
    cost: 380,
    prereq: ["market_cart_2", "clean_rows_2"],
    gates: [],
    effects: [{ kind: "special", id: "golden_field" }],
    description: "First 10s harvest score +25%.",
  },
  {
    id: "accountant",
    name: "Accountant",
    branch: "harvest",
    icon: "AC",
    cost: 1200,
    prereq: ["bulk_buyer_2"],
    gates: [],
    effects: [{ kind: "clearBonusPercent", amount: 10 }],
    description: "Final gold +10%.",
  },
  {
    id: "stone_chips",
    name: "Stone Chips",
    branch: "obstacles",
    icon: "O1",
    cost: 70,
    prereq: ["sharp_edge_2"],
    gates: [],
    effects: [{ kind: "rockScore", amount: 25 }],
    description: "Rock break +25 score.",
  },
  {
    id: "wood_haul",
    name: "Wood Haul",
    branch: "obstacles",
    icon: "O2",
    cost: 95,
    prereq: ["sharp_edge_2"],
    gates: [],
    effects: [{ kind: "treeScore", amount: 40 }],
    description: "Tree break +40 score.",
  },
  {
    id: "stump_grinder",
    name: "Stump Grinder",
    branch: "obstacles",
    icon: "SG",
    cost: 160,
    prereq: ["wood_haul"],
    gates: [],
    effects: [{ kind: "stumpNoCollision" }],
    description: "Tree stumps stop blocking after break.",
  },
  {
    id: "recoil_training",
    name: "Recoil Training",
    branch: "obstacles",
    icon: "RT",
    cost: 120,
    prereq: ["stone_chips"],
    gates: [],
    effects: [{ kind: "failedChopStunPercent", amount: -25 }],
    description: "Failed chop stun -25%.",
  },
  {
    id: "quarry_blade",
    name: "Quarry Blade",
    branch: "obstacles",
    icon: "QB",
    cost: 240,
    prereq: ["stone_chips"],
    gates: [],
    effects: [{ kind: "obstacleDamage", amount: 2 }],
    description: "Obstacle damage +2.",
  },
  {
    id: "clearcut",
    name: "Clearcut",
    branch: "obstacles",
    icon: "CC",
    cost: 360,
    prereq: ["wood_haul", "clean_sweep_2"],
    gates: [],
    effects: [{ kind: "special", id: "clearcut" }],
    description: "Obstacle breaks also cut nearby grass.",
  },
  {
    id: "lumberjack",
    name: "Lumberjack Ledger",
    branch: "obstacles",
    icon: "LJ",
    cost: 1400,
    prereq: ["clearcut"],
    gates: [],
    effects: [{ kind: "obstacleScorePercent", amount: 50 }],
    description: "Obstacle score +50%.",
  },
  {
    id: "seed_bombs",
    name: "Seed Bombs",
    branch: "bombs",
    icon: "BO",
    cost: 160,
    prereq: ["root_sharpen"],
    gates: [
      { kind: "bestClearPercent", mapSize: 10, percent: 15 },
      { kind: "lifetimeGrass", count: 500 },
    ],
    effects: [{ kind: "bombCount10m", amount: 3 }],
    description: "Spawn 3 bombs on the 10m map.",
  },
  {
    id: "fuse_training_1",
    name: "Fuse Training I",
    branch: "bombs",
    icon: "F1",
    cost: 190,
    prereq: ["seed_bombs"],
    gates: [],
    effects: [{ kind: "bombChainRadius", amount: 0.35 }],
    description: "Bomb chain radius +0.35m.",
  },
  {
    id: "blast_control_1",
    name: "Blast Control I",
    branch: "bombs",
    icon: "X1",
    cost: 220,
    prereq: ["seed_bombs"],
    gates: [],
    effects: [{ kind: "bombBlastRadius", amount: 0.2 }],
    description: "Bomb blast radius +0.20m.",
  },
  {
    id: "chain_payout_1",
    name: "Chain Payout I",
    branch: "bombs",
    icon: "CP",
    cost: 260,
    prereq: ["seed_bombs"],
    gates: [],
    effects: [{ kind: "bombChainScore", amount: 30 }],
    description: "Each extra chained bomb gives +30 score.",
  },
  {
    id: "fuse_training_2",
    name: "Fuse Training II",
    branch: "bombs",
    icon: "F2",
    cost: 780,
    prereq: ["fuse_training_1"],
    gates: [],
    effects: [{ kind: "bombChainRadius", amount: 0.35 }],
    description: "Bomb chain radius +0.35m.",
  },
  {
    id: "blast_control_2",
    name: "Blast Control II",
    branch: "bombs",
    icon: "X2",
    cost: 850,
    prereq: ["blast_control_1"],
    gates: [],
    effects: [{ kind: "bombBlastRadius", amount: 0.25 }],
    description: "Bomb blast radius +0.25m.",
  },
  {
    id: "harvest_detonation",
    name: "Harvest Detonation",
    branch: "bombs",
    icon: "HD",
    cost: 1800,
    prereq: ["fuse_training_2", "blast_control_2", "chain_payout_1"],
    gates: [],
    effects: [{ kind: "firstBombScorePercent", amount: 50 }],
    description: "First bomb each run scores +50%.",
  },
  {
    id: "open_acre",
    name: "Open Acre",
    branch: "land",
    icon: "LA",
    cost: 600,
    prereq: ["root_sharpen"],
    gates: [
      { kind: "bestClearPercent", mapSize: 10, percent: 30 },
      { kind: "bestBombChain", length: 2 },
    ],
    effects: [{ kind: "unlockMap", mapSize: 30 }],
    description: "Unlock the 30m map.",
  },
  {
    id: "dense_growth",
    name: "Dense Growth",
    branch: "land",
    icon: "DG",
    cost: 220,
    prereq: ["open_acre"],
    gates: [],
    effects: [{ kind: "initialGrassCount", amount: 120 }],
    description: "Base grass +120.",
  },
  {
    id: "fertile_soil",
    name: "Fertile Soil",
    branch: "land",
    icon: "FS",
    cost: 300,
    prereq: ["open_acre"],
    gates: [],
    effects: [{ kind: "grassScorePercent", amount: 10 }],
    description: "Grass score +10%.",
  },
  {
    id: "wide_sickle",
    name: "Wide Sickle",
    branch: "land",
    icon: "WS",
    cost: 1200,
    prereq: ["open_acre", "clean_sweep_2"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "wide_sickle" }],
    description: "Tool: range +0.25m, interval +150ms.",
  },
  {
    id: "fast_sickle",
    name: "Fast Sickle",
    branch: "land",
    icon: "FT",
    cost: 1200,
    prereq: ["open_acre", "quick_recovery_2"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "fast_sickle" }],
    description: "Tool: interval -150ms, range -0.05m.",
  },
  {
    id: "bomb_sickle",
    name: "Bomb Sickle",
    branch: "land",
    icon: "BS",
    cost: 1500,
    prereq: ["open_acre", "harvest_detonation"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "bomb_sickle" }],
    description: "Tool: bombs +2, chain payout +20%.",
  },
  {
    id: "alien_crop_mark",
    name: "Alien Crop Mark",
    branch: "spectacle",
    icon: "AM",
    cost: 1200,
    prereq: ["clean_sweep_2", "chain_payout_1"],
    gates: [],
    effects: [{ kind: "special", id: "alien_crop_mark" }],
    description: "Every 12s, stamps a 2.4m crop mark after a 0.4s warning.",
  },
  {
    id: "mower_laser",
    name: "Mower Laser",
    branch: "spectacle",
    icon: "LZ",
    cost: 1500,
    prereq: ["sharp_edge_2", "alien_crop_mark"],
    gates: [],
    effects: [{ kind: "special", id: "mower_laser" }],
    description: "Every 8th attack fires a 6m beam that can trigger bombs.",
  },
  {
    id: "tractor_license",
    name: "Tractor License",
    branch: "spectacle",
    icon: "TR",
    cost: 2200,
    prereq: ["open_acre", "wide_sickle", "long_day"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "tractor" }],
    description: "Tool: moving continuously mows a 1.2m front strip, turn response -15%.",
  },
];

export const SKILL_NODE_BY_ID: Record<string, SkillNode> = Object.fromEntries(
  SKILL_NODES.map((node) => [node.id, node]),
);
