export type ToolId = "default" | "wide_sickle" | "fast_sickle" | "bomb_sickle" | "tractor";

export type SkillBranch =
  | "root"
  | "blade"
  | "movement"
  | "harvest"
  | "obstacles"
  | "bombs"
  | "land"
  | "spectacle"
  | "summon";

export type UnlockGate =
  | { kind: "bestClearPercent"; mapSize: number; percent: number }
  | { kind: "lifetimeGrass"; count: number }
  | { kind: "bestBombChain"; length: number };

/** Summoned auto-abilities that fight alongside the player. */
export type SummonAbilityId =
  | "shadowClone"
  | "flyingScythe"
  | "tractorSummon"
  | "boomerang"
  | "lightning"
  | "drone"
  | "tornado";

/** Tunable stat each summon upgrade node nudges. */
export type SummonStatKind =
  | "count"
  | "damage"
  | "interval"
  | "radius"
  | "spins"
  | "duration"
  | "width"
  | "size"
  | "range";

export type SkillEffect =
  | { kind: "attackDamage"; amount: number }
  | { kind: "attackRange"; amount: number }
  | { kind: "attackInterval"; amount: number }
  | { kind: "moveSpeed"; amount: number }
  | { kind: "roundDurationPercent"; amount: number }
  | { kind: "goldDivisor"; amount: number }
  | { kind: "cleanPatchScore"; amount: number }
  | { kind: "clearBonusPercent"; amount: number }
  | { kind: "rockScore"; amount: number }
  | { kind: "treeScore"; amount: number }
  | { kind: "stumpNoCollision" }
  | { kind: "failedChopStunPercent"; amount: number }
  | { kind: "obstacleDamage"; amount: number }
  | { kind: "obstacleBreakGrassBonus" }
  | { kind: "obstacleScorePercent"; amount: number }
  | { kind: "bombCount10m"; amount: number }
  | { kind: "bombChainRadius"; amount: number }
  | { kind: "bombBlastRadius"; amount: number }
  | { kind: "bombChainScore"; amount: number }
  | { kind: "firstBombScorePercent"; amount: number }
  | { kind: "unlockMap"; mapSize: number }
  | { kind: "initialGrassCount"; amount: number }
  | { kind: "grassScorePercent"; amount: number }
  | { kind: "toolUnlock"; tool: ToolId }
  | { kind: "special"; id: "cyclone_cut" | "sprint_harvest" | "golden_field" | "clearcut" | "alien_crop_mark" | "mower_laser" }
  | { kind: "fireIgniteChance"; amount: number }
  | { kind: "fireDamagePerSecond"; amount: number }
  | { kind: "fireSpreadRadiusMeters"; amount: number }
  | { kind: "fireSpreadChancePerSecond"; amount: number }
  | { kind: "blueGrassSlow"; amount: number }
  | { kind: "timerGrassBonus"; amount: number }
  | { kind: "tallGrassGold"; amount: number }
  | { kind: "grassRegrowDelay"; amount: number }
  | { kind: "grassGrowSpeed"; amount: number }
  | { kind: "summon"; ability: SummonAbilityId; stat: SummonStatKind; amount: number }
  | { kind: "mapExpandCap"; amount: number }
  | { kind: "obstacleSurvey"; obstacle: "rock" | "tree" }
  | { kind: "obstacleSpawnRate"; amount: number }
  | { kind: "obstacleSize"; amount: number };

export interface SkillNode {
  id: string;
  name: string;
  branch: SkillBranch;
  icon: string;
  cost: number;
  prereq: string[];
  gates: UnlockGate[];
  effects: SkillEffect[];
  description: string;
}

export const SKILL_ROOT = "root_sharpen";

export const SKILL_NODES: SkillNode[] = [
  {
    id: "root_sharpen",
    name: "First Sharpening",
    branch: "root",
    icon: "R",
    cost: 10,
    prereq: [],
    gates: [],
    effects: [{ kind: "attackDamage", amount: 1 }],
    description: "Damage +1.",
  },
  {
    id: "sharp_edge_1",
    name: "Sharp Edge I",
    branch: "blade",
    icon: "B1",
    cost: 18,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "attackDamage", amount: 1 }],
    description: "Damage +1. Reaches one-hit grass with root.",
  },
  {
    id: "sharp_edge_2",
    name: "Sharp Edge II",
    branch: "blade",
    icon: "B2",
    cost: 60,
    prereq: ["sharp_edge_1"],
    gates: [],
    effects: [{ kind: "attackDamage", amount: 1 }],
    description: "Damage +1. Reaches obstacle break threshold.",
  },
  {
    id: "clean_sweep_1",
    name: "Clean Sweep I",
    branch: "blade",
    icon: "R1",
    cost: 28,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.1 }],
    description: "Attack range +0.10m.",
  },
  {
    id: "clean_sweep_2",
    name: "Clean Sweep II",
    branch: "blade",
    icon: "R2",
    cost: 90,
    prereq: ["clean_sweep_1"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.12 }],
    description: "Attack range +0.12m.",
  },
  {
    id: "wide_arc_1",
    name: "Wide Arc I",
    branch: "blade",
    icon: "WA1",
    cost: 140,
    prereq: ["clean_sweep_2"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.12 }],
    description: "Attack range +0.12m.",
  },
  {
    id: "wide_arc_2",
    name: "Wide Arc II",
    branch: "blade",
    icon: "WA2",
    cost: 210,
    prereq: ["wide_arc_1"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.14 }],
    description: "Attack range +0.14m.",
  },
  {
    id: "wide_arc_3",
    name: "Wide Arc III",
    branch: "blade",
    icon: "WA3",
    cost: 300,
    prereq: ["wide_arc_2"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.16 }],
    description: "Attack range +0.16m.",
  },
  {
    id: "grand_sweep_1",
    name: "Grand Sweep I",
    branch: "blade",
    icon: "GS1",
    cost: 400,
    prereq: ["wide_arc_3"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.15 }],
    description: "Attack range +0.15m.",
  },
  {
    id: "grand_sweep_2",
    name: "Grand Sweep II",
    branch: "blade",
    icon: "GS2",
    cost: 520,
    prereq: ["grand_sweep_1"],
    gates: [],
    effects: [{ kind: "attackRange", amount: 0.15 }],
    description: "Attack range +0.15m.",
  },
  {
    id: "quick_recovery_1",
    name: "Quick Recovery I",
    branch: "blade",
    icon: "Q1",
    cost: 35,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "attackInterval", amount: -100 }],
    description: "Attack interval -100ms.",
  },
  {
    id: "quick_recovery_2",
    name: "Quick Recovery II",
    branch: "blade",
    icon: "Q2",
    cost: 130,
    prereq: ["quick_recovery_1"],
    gates: [],
    effects: [{ kind: "attackInterval", amount: -100 }],
    description: "Attack interval -100ms.",
  },
  {
    id: "heavy_edge",
    name: "Heavy Edge",
    branch: "blade",
    icon: "HB",
    cost: 110,
    prereq: ["sharp_edge_2"],
    gates: [],
    effects: [
      { kind: "attackDamage", amount: 1 },
      { kind: "obstacleDamage", amount: 1 },
    ],
    description: "Damage +1 and obstacle damage +1.",
  },
  {
    id: "ember",
    name: "Ember Edge",
    branch: "blade",
    icon: "🔥",
    cost: 36,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "fireIgniteChance", amount: 0.05 }],
    description: "Hits have a 5% chance to ignite grass.",
  },
  {
    id: "burn1",
    name: "Burn Damage +",
    branch: "blade",
    icon: "🔥",
    cost: 34,
    prereq: ["ember"],
    gates: [],
    effects: [{ kind: "fireDamagePerSecond", amount: 0.35 }],
    description: "Fire damage +0.35/s.",
  },
  {
    id: "burn2",
    name: "Burn Damage ++",
    branch: "blade",
    icon: "🔥",
    cost: 52,
    prereq: ["burn1"],
    gates: [],
    effects: [{ kind: "fireDamagePerSecond", amount: 0.35 }],
    description: "Fire damage +0.35/s.",
  },
  {
    id: "burn3",
    name: "Burn Damage +++",
    branch: "blade",
    icon: "🔥",
    cost: 76,
    prereq: ["burn2"],
    gates: [],
    effects: [{ kind: "fireDamagePerSecond", amount: 0.35 }],
    description: "Fire damage +0.35/s.",
  },
  {
    id: "spread1",
    name: "Spread Radius +",
    branch: "blade",
    icon: "🔥",
    cost: 38,
    prereq: ["ember"],
    gates: [],
    effects: [{ kind: "fireSpreadRadiusMeters", amount: 0.05 }],
    description: "Fire spread radius +0.05m.",
  },
  {
    id: "spread2",
    name: "Spread Radius ++",
    branch: "blade",
    icon: "🔥",
    cost: 58,
    prereq: ["spread1"],
    gates: [],
    effects: [{ kind: "fireSpreadRadiusMeters", amount: 0.05 }],
    description: "Fire spread radius +0.05m.",
  },
  {
    id: "spread3",
    name: "Spread Radius +++",
    branch: "blade",
    icon: "🔥",
    cost: 84,
    prereq: ["spread2"],
    gates: [],
    effects: [{ kind: "fireSpreadRadiusMeters", amount: 0.05 }],
    description: "Fire spread radius +0.05m.",
  },
  {
    id: "kindle1",
    name: "Kindling +",
    branch: "blade",
    icon: "🔥",
    cost: 42,
    prereq: ["ember"],
    gates: [],
    effects: [{ kind: "fireSpreadChancePerSecond", amount: 0.06 }],
    description: "Fire spread speed +0.06/s.",
  },
  {
    id: "kindle2",
    name: "Kindling ++",
    branch: "blade",
    icon: "🔥",
    cost: 64,
    prereq: ["kindle1"],
    gates: [],
    effects: [{ kind: "fireSpreadChancePerSecond", amount: 0.06 }],
    description: "Fire spread speed +0.06/s.",
  },
  {
    id: "kindle3",
    name: "Kindling +++",
    branch: "blade",
    icon: "🔥",
    cost: 92,
    prereq: ["kindle2"],
    gates: [],
    effects: [{ kind: "fireSpreadChancePerSecond", amount: 0.06 }],
    description: "Fire spread speed +0.06/s.",
  },
  {
    id: "cyclone_cut",
    name: "Cyclone Cut",
    branch: "blade",
    icon: "CY",
    cost: 1200,
    prereq: ["clean_sweep_2", "quick_recovery_2"],
    gates: [],
    effects: [{ kind: "special", id: "cyclone_cut" }],
    description: "Every 6th attack performs a 0.85m circle cut.",
  },
  {
    id: "light_boots_1",
    name: "Light Boots I",
    branch: "movement",
    icon: "M1",
    cost: 14,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "moveSpeed", amount: 0.12 }],
    description: "Move speed +0.12.",
  },
  {
    id: "light_boots_2",
    name: "Light Boots II",
    branch: "movement",
    icon: "M2",
    cost: 55,
    prereq: ["light_boots_1"],
    gates: [],
    effects: [{ kind: "moveSpeed", amount: 0.14 }],
    description: "Move speed +0.14.",
  },
  {
    id: "field_rhythm_1",
    name: "Field Rhythm I",
    branch: "movement",
    icon: "T1",
    cost: 32,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "roundDurationPercent", amount: 8 }],
    description: "Round duration +8%.",
  },
  {
    id: "field_rhythm_2",
    name: "Field Rhythm II",
    branch: "movement",
    icon: "T2",
    cost: 125,
    prereq: ["field_rhythm_1"],
    gates: [],
    effects: [{ kind: "roundDurationPercent", amount: 8 }],
    description: "Round duration +8%.",
  },
  {
    id: "sprint_harvest",
    name: "Sprint Harvest",
    branch: "movement",
    icon: "SP",
    cost: 260,
    prereq: ["light_boots_2", "clean_rows_1"],
    gates: [],
    effects: [{ kind: "special", id: "sprint_harvest" }],
    description: "After a clean patch, move speed +20% for 2s.",
  },
  {
    id: "long_day",
    name: "Long Day",
    branch: "movement",
    icon: "LD",
    cost: 700,
    prereq: ["field_rhythm_2"],
    gates: [],
    effects: [{ kind: "roundDurationPercent", amount: 12 }],
    description: "Round duration +12%.",
  },
  {
    id: "market_cart_1",
    name: "Market Cart I",
    branch: "harvest",
    icon: "H1",
    cost: 20,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "goldDivisor", amount: -0.3 }],
    description: "Gold divisor 4.0 -> 3.7.",
  },
  {
    id: "market_cart_2",
    name: "Market Cart II",
    branch: "harvest",
    icon: "H2",
    cost: 80,
    prereq: ["market_cart_1"],
    gates: [],
    effects: [{ kind: "goldDivisor", amount: -0.3 }],
    description: "Gold divisor 3.7 -> 3.4.",
  },
  {
    id: "clean_rows_1",
    name: "Clean Mow I",
    branch: "harvest",
    icon: "C1",
    cost: 26,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "cleanPatchScore", amount: 8 }],
    description: "Driving-skill clean mow bonus +8 score.",
  },
  {
    id: "clean_rows_2",
    name: "Clean Mow II",
    branch: "harvest",
    icon: "C2",
    cost: 110,
    prereq: ["clean_rows_1"],
    gates: [],
    effects: [{ kind: "cleanPatchScore", amount: 14 }],
    description: "Driving-skill clean mow bonus +14 score.",
  },
  {
    id: "bulk_buyer_1",
    name: "Bulk Buyer I",
    branch: "harvest",
    icon: "P1",
    cost: 75,
    prereq: ["market_cart_1"],
    gates: [],
    effects: [{ kind: "clearBonusPercent", amount: 10 }],
    description: "Clear percent bonus +10%.",
  },
  {
    id: "bulk_buyer_2",
    name: "Bulk Buyer II",
    branch: "harvest",
    icon: "P2",
    cost: 210,
    prereq: ["bulk_buyer_1"],
    gates: [],
    effects: [{ kind: "clearBonusPercent", amount: 15 }],
    description: "Clear percent bonus +15%.",
  },
  {
    id: "golden_field",
    name: "Golden Field",
    branch: "harvest",
    icon: "GF",
    cost: 380,
    prereq: ["market_cart_2", "clean_rows_2"],
    gates: [],
    effects: [{ kind: "special", id: "golden_field" }],
    description: "First 10s harvest score +25%.",
  },
  {
    id: "accountant",
    name: "Accountant",
    branch: "harvest",
    icon: "AC",
    cost: 1200,
    prereq: ["bulk_buyer_2"],
    gates: [],
    effects: [{ kind: "clearBonusPercent", amount: 10 }],
    description: "Final gold +10%.",
  },
  {
    id: "stone_chips",
    name: "Stone Chips",
    branch: "obstacles",
    icon: "O1",
    cost: 70,
    prereq: ["sharp_edge_2"],
    gates: [],
    effects: [{ kind: "rockScore", amount: 25 }],
    description: "Rock break +25 score.",
  },
  {
    id: "wood_haul",
    name: "Wood Haul",
    branch: "obstacles",
    icon: "O2",
    cost: 95,
    prereq: ["sharp_edge_2"],
    gates: [],
    effects: [{ kind: "treeScore", amount: 40 }],
    description: "Tree break +40 score.",
  },
  {
    id: "stump_grinder",
    name: "Stump Grinder",
    branch: "obstacles",
    icon: "SG",
    cost: 160,
    prereq: ["wood_haul"],
    gates: [],
    effects: [{ kind: "stumpNoCollision" }],
    description: "Tree stumps stop blocking after break.",
  },
  {
    id: "recoil_training",
    name: "Recoil Training",
    branch: "obstacles",
    icon: "RT",
    cost: 120,
    prereq: ["stone_chips"],
    gates: [],
    effects: [{ kind: "failedChopStunPercent", amount: -25 }],
    description: "Failed chop stun -25%.",
  },
  {
    id: "quarry_blade",
    name: "Quarry Blade",
    branch: "obstacles",
    icon: "QB",
    cost: 240,
    prereq: ["stone_chips"],
    gates: [],
    effects: [{ kind: "obstacleDamage", amount: 2 }],
    description: "Obstacle damage +2.",
  },
  {
    id: "clearcut",
    name: "Clearcut",
    branch: "obstacles",
    icon: "CC",
    cost: 360,
    prereq: ["wood_haul", "clean_sweep_2"],
    gates: [],
    effects: [{ kind: "special", id: "clearcut" }],
    description: "Obstacle breaks also cut nearby grass.",
  },
  {
    id: "lumberjack",
    name: "Lumberjack Ledger",
    branch: "obstacles",
    icon: "LJ",
    cost: 1400,
    prereq: ["clearcut"],
    gates: [],
    effects: [{ kind: "obstacleScorePercent", amount: 50 }],
    description: "Obstacle score +50%.",
  },
  {
    id: "seed_bombs",
    name: "Seed Bombs",
    branch: "bombs",
    icon: "BO",
    cost: 160,
    prereq: ["root_sharpen"],
    gates: [
      { kind: "bestClearPercent", mapSize: 10, percent: 15 },
      { kind: "lifetimeGrass", count: 500 },
    ],
    effects: [{ kind: "bombCount10m", amount: 3 }],
    description: "Spawn 3 bombs on the 10m map.",
  },
  {
    id: "fuse_training_1",
    name: "Fuse Training I",
    branch: "bombs",
    icon: "F1",
    cost: 190,
    prereq: ["seed_bombs"],
    gates: [],
    effects: [{ kind: "bombChainRadius", amount: 0.35 }],
    description: "Bomb chain radius +0.35m.",
  },
  {
    id: "blast_control_1",
    name: "Blast Control I",
    branch: "bombs",
    icon: "X1",
    cost: 220,
    prereq: ["seed_bombs"],
    gates: [],
    effects: [{ kind: "bombBlastRadius", amount: 0.2 }],
    description: "Bomb blast radius +0.20m.",
  },
  {
    id: "chain_payout_1",
    name: "Chain Payout I",
    branch: "bombs",
    icon: "CP",
    cost: 260,
    prereq: ["seed_bombs"],
    gates: [],
    effects: [{ kind: "bombChainScore", amount: 30 }],
    description: "Each extra chained bomb gives +30 score.",
  },
  {
    id: "fuse_training_2",
    name: "Fuse Training II",
    branch: "bombs",
    icon: "F2",
    cost: 780,
    prereq: ["fuse_training_1"],
    gates: [],
    effects: [{ kind: "bombChainRadius", amount: 0.35 }],
    description: "Bomb chain radius +0.35m.",
  },
  {
    id: "blast_control_2",
    name: "Blast Control II",
    branch: "bombs",
    icon: "X2",
    cost: 850,
    prereq: ["blast_control_1"],
    gates: [],
    effects: [{ kind: "bombBlastRadius", amount: 0.25 }],
    description: "Bomb blast radius +0.25m.",
  },
  {
    id: "harvest_detonation",
    name: "Harvest Detonation",
    branch: "bombs",
    icon: "HD",
    cost: 1800,
    prereq: ["fuse_training_2", "blast_control_2", "chain_payout_1"],
    gates: [],
    effects: [{ kind: "firstBombScorePercent", amount: 50 }],
    description: "First bomb each run scores +50%.",
  },
  {
    id: "open_acre",
    name: "Open Acre",
    branch: "land",
    icon: "LA",
    cost: 600,
    prereq: ["root_sharpen"],
    gates: [
      { kind: "bestClearPercent", mapSize: 10, percent: 30 },
      { kind: "bestBombChain", length: 2 },
    ],
    effects: [{ kind: "unlockMap", mapSize: 30 }],
    description: "Unlock the 30m map.",
  },
  {
    id: "dense_growth",
    name: "Dense Growth",
    branch: "land",
    icon: "DG",
    cost: 220,
    prereq: ["open_acre"],
    gates: [],
    effects: [{ kind: "initialGrassCount", amount: 120 }],
    description: "Base grass +120.",
  },
  {
    id: "fertile_soil",
    name: "Fertile Soil",
    branch: "land",
    icon: "FS",
    cost: 300,
    prereq: ["open_acre"],
    gates: [],
    effects: [{ kind: "grassScorePercent", amount: 10 }],
    description: "Grass score +10%.",
  },
  {
    id: "wide_sickle",
    name: "Wide Sickle",
    branch: "land",
    icon: "WS",
    cost: 1200,
    prereq: ["open_acre", "clean_sweep_2"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "wide_sickle" }],
    description: "Tool: range +0.25m, interval +150ms.",
  },
  {
    id: "fast_sickle",
    name: "Fast Sickle",
    branch: "land",
    icon: "FT",
    cost: 1200,
    prereq: ["open_acre", "quick_recovery_2"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "fast_sickle" }],
    description: "Tool: interval -150ms, range -0.05m.",
  },
  {
    id: "bomb_sickle",
    name: "Bomb Sickle",
    branch: "land",
    icon: "BS",
    cost: 1500,
    prereq: ["open_acre", "harvest_detonation"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "bomb_sickle" }],
    description: "Tool: bombs +2, chain payout +20%.",
  },
  {
    id: "alien_crop_mark",
    name: "Alien Crop Mark",
    branch: "spectacle",
    icon: "AM",
    cost: 1200,
    prereq: ["clean_sweep_2", "chain_payout_1"],
    gates: [],
    effects: [{ kind: "special", id: "alien_crop_mark" }],
    description: "Every 12s, stamps a 2.4m crop mark after a 0.4s warning.",
  },
  {
    id: "mower_laser",
    name: "Mower Laser",
    branch: "spectacle",
    icon: "LZ",
    cost: 1500,
    prereq: ["sharp_edge_2", "alien_crop_mark"],
    gates: [],
    effects: [{ kind: "special", id: "mower_laser" }],
    description: "Every 8th attack fires a 6m beam that can trigger bombs.",
  },
  {
    id: "tractor_license",
    name: "Tractor License",
    branch: "spectacle",
    icon: "TR",
    cost: 2200,
    prereq: ["open_acre", "wide_sickle", "long_day"],
    gates: [],
    effects: [{ kind: "toolUnlock", tool: "tractor" }],
    description: "Tool: moving continuously mows a 1.2m front strip, turn response -15%.",
  },
  {
    id: "grasslore",
    name: "Grass Lore",
    branch: "land",
    icon: "🌿",
    cost: 20,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [],
    description: "Reveals special grass types.",
  },
  {
    id: "bluefoot",
    name: "Blue Foot",
    branch: "land",
    icon: "🔵",
    cost: 28,
    prereq: ["grasslore"],
    gates: [],
    effects: [{ kind: "blueGrassSlow", amount: -0.17 }],
    description: "Blue grass slows only 1/6 instead of 1/3.",
  },
  {
    id: "timerboon",
    name: "Timer Boon",
    branch: "land",
    icon: "⏱️",
    cost: 32,
    prereq: ["grasslore"],
    gates: [],
    effects: [{ kind: "timerGrassBonus", amount: 1 }],
    description: "Timer grass restores +1s extra.",
  },
  {
    id: "fastgrowth",
    name: "Fast Regrowth",
    branch: "land",
    icon: "🌱",
    cost: 36,
    prereq: ["grasslore"],
    gates: [],
    effects: [{ kind: "grassRegrowDelay", amount: -6 }],
    description: "Grass regrows 6s faster.",
  },
  {
    id: "tallbounty",
    name: "Tall Bounty",
    branch: "land",
    icon: "💰",
    cost: 30,
    prereq: ["grasslore"],
    gates: [],
    effects: [{ kind: "tallGrassGold", amount: 2 }],
    description: "Tall grass gives +2 bonus gold.",
  },
  {
    id: "grow_speed_1",
    name: "Fast Growth I",
    branch: "land",
    icon: "🌱",
    cost: 50,
    prereq: ["fastgrowth"],
    gates: [],
    effects: [{ kind: "grassGrowSpeed", amount: 1.0 }],
    description: "Grass grows 1s faster.",
  },
  {
    id: "grow_speed_2",
    name: "Fast Growth II",
    branch: "land",
    icon: "🌿",
    cost: 90,
    prereq: ["grow_speed_1"],
    gates: [],
    effects: [{ kind: "grassGrowSpeed", amount: 1.0 }],
    description: "Grass grows 1s faster.",
  },
  {
    id: "grow_speed_3",
    name: "Fast Growth III",
    branch: "land",
    icon: "🌾",
    cost: 140,
    prereq: ["grow_speed_2"],
    gates: [],
    effects: [{ kind: "grassGrowSpeed", amount: 1.2 }],
    description: "Grass grows 1.2s faster.",
  },
  {
    id: "grow_speed_4",
    name: "Fast Growth IV",
    branch: "land",
    icon: "🎋",
    cost: 210,
    prereq: ["grow_speed_3"],
    gates: [],
    effects: [{ kind: "grassGrowSpeed", amount: 1.2 }],
    description: "Grass grows 1.2s faster.",
  },
  {
    id: "grow_speed_5",
    name: "Fast Growth V",
    branch: "land",
    icon: "🌳",
    cost: 300,
    prereq: ["grow_speed_4"],
    gates: [],
    effects: [{ kind: "grassGrowSpeed", amount: 1.6 }],
    description: "Grass grows 1.6s faster.",
  },

  // ── Summons branch: auto-abilities that fight alongside the player ────────
  {
    id: "summon_codex",
    name: "Summoner's Codex",
    branch: "summon",
    icon: "✨",
    cost: 120,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [],
    description: "Opens the summon branch of auto-fighting abilities.",
  },

  // Shadow Clone
  {
    id: "summon_shadow",
    name: "Shadow Clone",
    branch: "summon",
    icon: "🌑",
    cost: 220,
    prereq: ["summon_codex"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "count", amount: 1 }],
    description: "Summon a shadow clone that mows grass at random spots (half your damage).",
  },
  {
    id: "shadow_count_2",
    name: "Shadow Clone +1",
    branch: "summon",
    icon: "🌑",
    cost: 320,
    prereq: ["summon_shadow"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "count", amount: 1 }],
    description: "Up to 2 shadow clones at once.",
  },
  {
    id: "shadow_count_3",
    name: "Shadow Clone +1",
    branch: "summon",
    icon: "🌑",
    cost: 440,
    prereq: ["shadow_count_2"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "count", amount: 1 }],
    description: "Up to 3 shadow clones at once.",
  },
  {
    id: "shadow_dmg_1",
    name: "Clone Edge I",
    branch: "summon",
    icon: "🌑",
    cost: 200,
    prereq: ["summon_shadow"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "damage", amount: 0.17 }],
    description: "Shadow clone damage +17% of player.",
  },
  {
    id: "shadow_dmg_2",
    name: "Clone Edge II",
    branch: "summon",
    icon: "🌑",
    cost: 300,
    prereq: ["shadow_dmg_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "damage", amount: 0.17 }],
    description: "Shadow clone damage +17% of player.",
  },
  {
    id: "shadow_dmg_3",
    name: "Clone Edge III",
    branch: "summon",
    icon: "🌑",
    cost: 420,
    prereq: ["shadow_dmg_2"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "damage", amount: 0.16 }],
    description: "Shadow clone reaches full player damage.",
  },
  {
    id: "shadow_cd_1",
    name: "Clone Recall I",
    branch: "summon",
    icon: "🌑",
    cost: 180,
    prereq: ["summon_shadow"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "interval", amount: -0.5 }],
    description: "Shadow clones appear 0.5s sooner.",
  },
  {
    id: "shadow_cd_2",
    name: "Clone Recall II",
    branch: "summon",
    icon: "🌑",
    cost: 270,
    prereq: ["shadow_cd_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "interval", amount: -0.5 }],
    description: "Shadow clones appear 0.5s sooner.",
  },
  {
    id: "shadow_cd_3",
    name: "Clone Recall III",
    branch: "summon",
    icon: "🌑",
    cost: 360,
    prereq: ["shadow_cd_2"],
    gates: [],
    effects: [{ kind: "summon", ability: "shadowClone", stat: "interval", amount: -0.5 }],
    description: "Shadow clones appear 0.5s sooner.",
  },

  // Flying Scythe
  {
    id: "summon_scythe",
    name: "Flying Scythe",
    branch: "summon",
    icon: "🔪",
    cost: 240,
    prereq: ["summon_codex"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "count", amount: 1 }],
    description: "Launch a scythe forward that stops and spins, mowing grass.",
  },
  {
    id: "scythe_count_2",
    name: "Scythe Fan +1",
    branch: "summon",
    icon: "🔪",
    cost: 320,
    prereq: ["summon_scythe"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "count", amount: 1 }],
    description: "Throw 2 scythes spread in a fan.",
  },
  {
    id: "scythe_count_3",
    name: "Scythe Fan +1",
    branch: "summon",
    icon: "🔪",
    cost: 400,
    prereq: ["scythe_count_2"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "count", amount: 1 }],
    description: "Throw 3 scythes spread in a fan.",
  },
  {
    id: "scythe_count_4",
    name: "Scythe Fan +1",
    branch: "summon",
    icon: "🔪",
    cost: 500,
    prereq: ["scythe_count_3"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "count", amount: 1 }],
    description: "Throw 4 scythes spread in a fan.",
  },
  {
    id: "scythe_count_5",
    name: "Scythe Fan +1",
    branch: "summon",
    icon: "🔪",
    cost: 620,
    prereq: ["scythe_count_4"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "count", amount: 1 }],
    description: "Throw 5 scythes spread in a fan.",
  },
  {
    id: "scythe_dmg_1",
    name: "Scythe Edge I",
    branch: "summon",
    icon: "🔪",
    cost: 220,
    prereq: ["summon_scythe"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "damage", amount: 0.13 }],
    description: "Scythe damage +13% of player.",
  },
  {
    id: "scythe_dmg_2",
    name: "Scythe Edge II",
    branch: "summon",
    icon: "🔪",
    cost: 320,
    prereq: ["scythe_dmg_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "damage", amount: 0.13 }],
    description: "Scythe damage +13% of player.",
  },
  {
    id: "scythe_dmg_3",
    name: "Scythe Edge III",
    branch: "summon",
    icon: "🔪",
    cost: 440,
    prereq: ["scythe_dmg_2"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "damage", amount: 0.14 }],
    description: "Scythe reaches full player damage.",
  },
  {
    id: "scythe_radius_1",
    name: "Wide Spin I",
    branch: "summon",
    icon: "🔪",
    cost: 260,
    prereq: ["summon_scythe"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "radius", amount: 0.15 }],
    description: "Scythe spin radius +0.15m.",
  },
  {
    id: "scythe_radius_2",
    name: "Wide Spin II",
    branch: "summon",
    icon: "🔪",
    cost: 360,
    prereq: ["scythe_radius_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "radius", amount: 0.15 }],
    description: "Scythe spin radius +0.15m.",
  },
  {
    id: "scythe_spin_1",
    name: "Long Spin I",
    branch: "summon",
    icon: "🔪",
    cost: 240,
    prereq: ["summon_scythe"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "spins", amount: 2 }],
    description: "Scythe spins 2 more times before fading.",
  },
  {
    id: "scythe_spin_2",
    name: "Long Spin II",
    branch: "summon",
    icon: "🔪",
    cost: 340,
    prereq: ["scythe_spin_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "flyingScythe", stat: "spins", amount: 2 }],
    description: "Scythe spins 2 more times before fading.",
  },

  // Tractor Summon
  {
    id: "summon_tractor",
    name: "Tractor Call",
    branch: "summon",
    icon: "🚜",
    cost: 300,
    prereq: ["summon_codex"],
    gates: [],
    effects: [{ kind: "summon", ability: "tractorSummon", stat: "count", amount: 1 }],
    description: "Summon a tractor that drives across the map mowing a wide strip.",
  },
  {
    id: "tractor_width_1",
    name: "Wide Deck I",
    branch: "summon",
    icon: "🚜",
    cost: 260,
    prereq: ["summon_tractor"],
    gates: [],
    effects: [{ kind: "summon", ability: "tractorSummon", stat: "width", amount: 0.4 }],
    description: "Tractor strip width +0.4m.",
  },
  {
    id: "tractor_width_2",
    name: "Wide Deck II",
    branch: "summon",
    icon: "🚜",
    cost: 360,
    prereq: ["tractor_width_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "tractorSummon", stat: "width", amount: 0.4 }],
    description: "Tractor strip width +0.4m.",
  },
  {
    id: "tractor_dmg_1",
    name: "Tractor Blades I",
    branch: "summon",
    icon: "🚜",
    cost: 240,
    prereq: ["summon_tractor"],
    gates: [],
    effects: [{ kind: "summon", ability: "tractorSummon", stat: "damage", amount: 0.2 }],
    description: "Tractor damage +20% of player.",
  },
  {
    id: "tractor_dmg_2",
    name: "Tractor Blades II",
    branch: "summon",
    icon: "🚜",
    cost: 340,
    prereq: ["tractor_dmg_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "tractorSummon", stat: "damage", amount: 0.2 }],
    description: "Tractor damage +20% of player.",
  },
  {
    id: "tractor_cd_1",
    name: "Quick Ignition I",
    branch: "summon",
    icon: "🚜",
    cost: 220,
    prereq: ["summon_tractor"],
    gates: [],
    effects: [{ kind: "summon", ability: "tractorSummon", stat: "interval", amount: -1 }],
    description: "Tractor arrives 1s sooner.",
  },
  {
    id: "tractor_cd_2",
    name: "Quick Ignition II",
    branch: "summon",
    icon: "🚜",
    cost: 320,
    prereq: ["tractor_cd_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "tractorSummon", stat: "interval", amount: -1 }],
    description: "Tractor arrives 1s sooner.",
  },

  // Boomerang
  {
    id: "summon_boomerang",
    name: "Boomerang Scythe",
    branch: "summon",
    icon: "🪃",
    cost: 240,
    prereq: ["summon_codex"],
    gates: [],
    effects: [{ kind: "summon", ability: "boomerang", stat: "count", amount: 1 }],
    description: "Throw a scythe that flies out and returns, cutting both ways.",
  },
  {
    id: "boom_count_2",
    name: "Boomerang +1",
    branch: "summon",
    icon: "🪃",
    cost: 340,
    prereq: ["summon_boomerang"],
    gates: [],
    effects: [{ kind: "summon", ability: "boomerang", stat: "count", amount: 1 }],
    description: "Throw 2 boomerangs in a fan.",
  },
  {
    id: "boom_count_3",
    name: "Boomerang +1",
    branch: "summon",
    icon: "🪃",
    cost: 460,
    prereq: ["boom_count_2"],
    gates: [],
    effects: [{ kind: "summon", ability: "boomerang", stat: "count", amount: 1 }],
    description: "Throw 3 boomerangs in a fan.",
  },
  {
    id: "boom_dmg_1",
    name: "Boomerang Edge I",
    branch: "summon",
    icon: "🪃",
    cost: 240,
    prereq: ["summon_boomerang"],
    gates: [],
    effects: [{ kind: "summon", ability: "boomerang", stat: "damage", amount: 0.2 }],
    description: "Boomerang damage +20% of player.",
  },
  {
    id: "boom_dmg_2",
    name: "Boomerang Edge II",
    branch: "summon",
    icon: "🪃",
    cost: 340,
    prereq: ["boom_dmg_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "boomerang", stat: "damage", amount: 0.2 }],
    description: "Boomerang damage +20% of player.",
  },
  {
    id: "boom_range_1",
    name: "Long Throw I",
    branch: "summon",
    icon: "🪃",
    cost: 220,
    prereq: ["summon_boomerang"],
    gates: [],
    effects: [{ kind: "summon", ability: "boomerang", stat: "range", amount: 0.6 }],
    description: "Boomerang flies 0.6m farther.",
  },
  {
    id: "boom_range_2",
    name: "Long Throw II",
    branch: "summon",
    icon: "🪃",
    cost: 320,
    prereq: ["boom_range_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "boomerang", stat: "range", amount: 0.6 }],
    description: "Boomerang flies 0.6m farther.",
  },

  // Lightning
  {
    id: "summon_lightning",
    name: "Lightning Strike",
    branch: "summon",
    icon: "⚡",
    cost: 260,
    prereq: ["summon_codex"],
    gates: [],
    effects: [{ kind: "summon", ability: "lightning", stat: "count", amount: 1 }],
    description: "Strike a random spot with lightning that burns grass.",
  },
  {
    id: "light_count_2",
    name: "Storm +1",
    branch: "summon",
    icon: "⚡",
    cost: 360,
    prereq: ["summon_lightning"],
    gates: [],
    effects: [{ kind: "summon", ability: "lightning", stat: "count", amount: 1 }],
    description: "2 lightning strikes per cast.",
  },
  {
    id: "light_count_3",
    name: "Storm +1",
    branch: "summon",
    icon: "⚡",
    cost: 480,
    prereq: ["light_count_2"],
    gates: [],
    effects: [{ kind: "summon", ability: "lightning", stat: "count", amount: 1 }],
    description: "3 lightning strikes per cast.",
  },
  {
    id: "light_radius_1",
    name: "Wide Bolt I",
    branch: "summon",
    icon: "⚡",
    cost: 240,
    prereq: ["summon_lightning"],
    gates: [],
    effects: [{ kind: "summon", ability: "lightning", stat: "radius", amount: 0.2 }],
    description: "Lightning radius +0.2m.",
  },
  {
    id: "light_radius_2",
    name: "Wide Bolt II",
    branch: "summon",
    icon: "⚡",
    cost: 340,
    prereq: ["light_radius_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "lightning", stat: "radius", amount: 0.2 }],
    description: "Lightning radius +0.2m.",
  },
  {
    id: "light_cd_1",
    name: "Charged I",
    branch: "summon",
    icon: "⚡",
    cost: 240,
    prereq: ["summon_lightning"],
    gates: [],
    effects: [{ kind: "summon", ability: "lightning", stat: "interval", amount: -1 }],
    description: "Lightning strikes 1s sooner.",
  },
  {
    id: "light_cd_2",
    name: "Charged II",
    branch: "summon",
    icon: "⚡",
    cost: 340,
    prereq: ["light_cd_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "lightning", stat: "interval", amount: -1 }],
    description: "Lightning strikes 1s sooner.",
  },

  // Drone
  {
    id: "summon_drone",
    name: "Mower Drone",
    branch: "summon",
    icon: "🛸",
    cost: 280,
    prereq: ["summon_codex"],
    gates: [],
    effects: [{ kind: "summon", ability: "drone", stat: "count", amount: 1 }],
    description: "Deploy a drone that roams the map mowing grass below it.",
  },
  {
    id: "drone_count_2",
    name: "Drone +1",
    branch: "summon",
    icon: "🛸",
    cost: 420,
    prereq: ["summon_drone"],
    gates: [],
    effects: [{ kind: "summon", ability: "drone", stat: "count", amount: 1 }],
    description: "Up to 2 drones at once.",
  },
  {
    id: "drone_radius_1",
    name: "Wide Sweep I",
    branch: "summon",
    icon: "🛸",
    cost: 240,
    prereq: ["summon_drone"],
    gates: [],
    effects: [{ kind: "summon", ability: "drone", stat: "radius", amount: 0.2 }],
    description: "Drone mow radius +0.2m.",
  },
  {
    id: "drone_radius_2",
    name: "Wide Sweep II",
    branch: "summon",
    icon: "🛸",
    cost: 340,
    prereq: ["drone_radius_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "drone", stat: "radius", amount: 0.2 }],
    description: "Drone mow radius +0.2m.",
  },
  {
    id: "drone_dur_1",
    name: "Long Flight I",
    branch: "summon",
    icon: "🛸",
    cost: 240,
    prereq: ["summon_drone"],
    gates: [],
    effects: [{ kind: "summon", ability: "drone", stat: "duration", amount: 2 }],
    description: "Drone stays 2s longer.",
  },
  {
    id: "drone_dur_2",
    name: "Long Flight II",
    branch: "summon",
    icon: "🛸",
    cost: 340,
    prereq: ["drone_dur_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "drone", stat: "duration", amount: 2 }],
    description: "Drone stays 2s longer.",
  },
  {
    id: "drone_dmg_1",
    name: "Drone Blades",
    branch: "summon",
    icon: "🛸",
    cost: 320,
    prereq: ["summon_drone"],
    gates: [],
    effects: [{ kind: "summon", ability: "drone", stat: "damage", amount: 0.2 }],
    description: "Drone damage +20% of player.",
  },

  // Tornado
  {
    id: "summon_tornado",
    name: "Tornado",
    branch: "summon",
    icon: "🌪️",
    cost: 320,
    prereq: ["summon_codex"],
    gates: [],
    effects: [{ kind: "summon", ability: "tornado", stat: "count", amount: 1 }],
    description: "Conjure a tornado that weaves across the map sweeping grass.",
  },
  {
    id: "torn_size_1",
    name: "Bigger Funnel I",
    branch: "summon",
    icon: "🌪️",
    cost: 280,
    prereq: ["summon_tornado"],
    gates: [],
    effects: [{ kind: "summon", ability: "tornado", stat: "size", amount: 0.3 }],
    description: "Tornado radius +0.3m.",
  },
  {
    id: "torn_size_2",
    name: "Bigger Funnel II",
    branch: "summon",
    icon: "🌪️",
    cost: 380,
    prereq: ["torn_size_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "tornado", stat: "size", amount: 0.3 }],
    description: "Tornado radius +0.3m.",
  },
  {
    id: "torn_dur_1",
    name: "Lasting Storm I",
    branch: "summon",
    icon: "🌪️",
    cost: 260,
    prereq: ["summon_tornado"],
    gates: [],
    effects: [{ kind: "summon", ability: "tornado", stat: "duration", amount: 1.5 }],
    description: "Tornado lasts 1.5s longer.",
  },
  {
    id: "torn_dur_2",
    name: "Lasting Storm II",
    branch: "summon",
    icon: "🌪️",
    cost: 360,
    prereq: ["torn_dur_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "tornado", stat: "duration", amount: 1.5 }],
    description: "Tornado lasts 1.5s longer.",
  },
  {
    id: "torn_dmg_1",
    name: "Tornado Force I",
    branch: "summon",
    icon: "🌪️",
    cost: 300,
    prereq: ["summon_tornado"],
    gates: [],
    effects: [{ kind: "summon", ability: "tornado", stat: "damage", amount: 0.2 }],
    description: "Tornado damage +20% of player.",
  },
  {
    id: "torn_dmg_2",
    name: "Tornado Force II",
    branch: "summon",
    icon: "🌪️",
    cost: 400,
    prereq: ["torn_dmg_1"],
    gates: [],
    effects: [{ kind: "summon", ability: "tornado", stat: "damage", amount: 0.2 }],
    description: "Tornado damage +20% of player.",
  },

  // ── Wide Lands: raise the cap on how far the map auto-grows ───────────────
  {
    id: "wide_lands_1",
    name: "Survey Stakes I",
    branch: "land",
    icon: "🗺️",
    cost: 180,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "mapExpandCap", amount: 6 }],
    description: "Map can auto-grow up to +6m larger.",
  },
  {
    id: "wide_lands_2",
    name: "Survey Stakes II",
    branch: "land",
    icon: "🗺️",
    cost: 320,
    prereq: ["wide_lands_1"],
    gates: [],
    effects: [{ kind: "mapExpandCap", amount: 8 }],
    description: "Map can auto-grow up to +8m more.",
  },
  {
    id: "wide_lands_3",
    name: "Survey Stakes III",
    branch: "land",
    icon: "🗺️",
    cost: 480,
    prereq: ["wide_lands_2"],
    gates: [],
    effects: [{ kind: "mapExpandCap", amount: 10 }],
    description: "Map can auto-grow up to +10m more.",
  },
  {
    id: "wide_lands_4",
    name: "Survey Stakes IV",
    branch: "land",
    icon: "🗺️",
    cost: 680,
    prereq: ["wide_lands_3"],
    gates: [],
    effects: [{ kind: "mapExpandCap", amount: 12 }],
    description: "Map can auto-grow up to +12m more.",
  },

  // ── Field hazards: unlock rocks/trees that spawn over time ────────────────
  {
    id: "survey_rock",
    name: "Rock Survey",
    branch: "obstacles",
    icon: "🪨",
    cost: 160,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "obstacleSurvey", obstacle: "rock" }],
    description: "Rocks start appearing (1 every 10s). They block grass nearby.",
  },
  {
    id: "survey_tree",
    name: "Tree Survey",
    branch: "obstacles",
    icon: "🌳",
    cost: 190,
    prereq: ["root_sharpen"],
    gates: [],
    effects: [{ kind: "obstacleSurvey", obstacle: "tree" }],
    description: "Trees start appearing. Grass grows faster around them.",
  },
  {
    id: "field_churn_1",
    name: "Field Churn I",
    branch: "obstacles",
    icon: "⛏️",
    cost: 220,
    prereq: ["survey_rock"],
    gates: [],
    effects: [{ kind: "obstacleSpawnRate", amount: -2 }],
    description: "Obstacles appear 2s sooner.",
  },
  {
    id: "field_churn_2",
    name: "Field Churn II",
    branch: "obstacles",
    icon: "⛏️",
    cost: 320,
    prereq: ["field_churn_1"],
    gates: [],
    effects: [{ kind: "obstacleSpawnRate", amount: -2 }],
    description: "Obstacles appear 2s sooner.",
  },
  {
    id: "boulder_lore_1",
    name: "Boulder Lore I",
    branch: "obstacles",
    icon: "🗿",
    cost: 240,
    prereq: ["survey_rock"],
    gates: [],
    effects: [{ kind: "obstacleSize", amount: 0.3 }],
    description: "Obstacles spawn larger (tougher, worth more).",
  },
  {
    id: "boulder_lore_2",
    name: "Boulder Lore II",
    branch: "obstacles",
    icon: "🗿",
    cost: 360,
    prereq: ["boulder_lore_1"],
    gates: [],
    effects: [{ kind: "obstacleSize", amount: 0.4 }],
    description: "Obstacles spawn even larger.",
  },
];

export const SKILL_NODE_BY_ID: Record<string, SkillNode> = Object.fromEntries(
  SKILL_NODES.map((node) => [node.id, node]),
);
